import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./notification.css";
import messageService from "../services/messageService";

const NotificationsPage = () => {
  const navigate = useNavigate();

  // مصفوفة الإشعارات القادمة من الآدمن وقاعدة البيانات
  const [adminNotifications, setAdminNotifications] = useState([]);
  const [notificationsLoading, setNotificationsLoading] = useState(true);
  const [notificationsError, setNotificationsError] = useState("");

  useEffect(() => {
    const fetchNotifications = async () => {
      try {
        setNotificationsLoading(true);
        setNotificationsError("");

        const response = await messageService.getMyMessages();

        // handlerFactory.getAll answers { status, results, doc }
        const messages = Array.isArray(response?.doc) ? response.doc : [];

        setAdminNotifications(
          messages.map((message) => ({
            id: message._id,
            title: message.title,
            message:
              typeof message.body === "object"
                ? message.body?.message || JSON.stringify(message.body)
                : message.body,
            time: message.createdAt,
            type: "info",
            unread: !message.isRead,
          })),
        );
      } catch (error) {
        console.error("Failed to fetch notifications:", error);

        setNotificationsError(
          error?.response?.data?.message || "Failed to load notifications.",
        );
      } finally {
        setNotificationsLoading(false);
      }
    };

    fetchNotifications();
  }, []);
  // دالة النقر على الإشعار: تحوله لمقروء وتنقل العميل لداشبورد السيرفرات

  const handleActionClick = async (id) => {
    try {
      const notification = adminNotifications.find((item) => item.id === id);

      if (notification?.unread) {
        await messageService.markAsRead(id);

        window.dispatchEvent(new Event("notificationsUpdated"));

        setAdminNotifications((currentNotifications) =>
          currentNotifications.map((item) =>
            item.id === id ? { ...item, unread: false } : item,
          ),
        );
      }

      navigate("/dashboard?tab=overview");
    } catch (error) {
      console.error("Failed to mark notification as read:", error);
    }
  };

  return (
    <div className="servergo-notifications-page" dir="ltr">
      <div className="notif-page-container">
        {/* هيدر الصفحة الفاتح الأنيق */}
        <div className="notif-page-header">
          <div>
            <h1>Account Notifications</h1>
            <p>
              Stay updated with instant deployment statuses and server billing
              alerts generated by administration.
            </p>
          </div>
          <button
            className="mark-all-read-btn"
            onClick={() =>
              setAdminNotifications(
                adminNotifications.map((n) => ({ ...n, unread: false })),
              )
            }
          >
            Mark all as read
          </button>
        </div>

        {/* قائمة عرض الإشعارات الرأسية الفخمة */}
        <div className="notif-cards-stack-list">
          {notificationsLoading ? (
            <div className="empty-notif-box">
              <i className="fa-solid fa-spinner"></i>
              <h3>Loading your notifications...</h3>
            </div>
          ) : notificationsError ? (
            <div className="empty-notif-box">
              <i className="fa-solid fa-triangle-exclamation"></i>
              <h3>Could not load notifications</h3>
              <p>{notificationsError}</p>
            </div>
          ) : adminNotifications.length === 0 ? (
            <div className="empty-notif-box">
              <i className="fa-solid fa-bell-slash"></i>
              <h3>Your inbox is clean</h3>
              <p>
                No platform alerts or administrator logs found for your profile
                node.
              </p>
            </div>
          ) : (
            adminNotifications.map((notif) => (
              <div
                key={notif.id}
                className={`notif-full-card-item ${notif.unread ? "is-unread-card" : ""}`}
                onClick={() => handleActionClick(notif.id)}
              >
                {/* عمود التمييز اللوني والرمز التعبيري */}
                <div className={`notif-icon-side-box ${notif.type}`}>
                  {notif.type === "success" ? (
                    <i className="fa-solid fa-circle-check"></i>
                  ) : (
                    <i className="fa-solid fa-triangle-exclamation"></i>
                  )}
                </div>

                {/* النصوص والتفاصيل */}
                <div className="notif-body-text-box">
                  <div className="notif-title-row-line">
                    <h3>{notif.title}</h3>
                    <span className="notif-timestamp-txt">{notif.time}</span>
                  </div>
                  <p>{notif.message}</p>
                  <span className="notif-redirect-action-hint">
                    Click to open your User Dashboard →
                  </span>
                </div>

                {/* نقطة الإشعارات الموف المشعة غير المقروءة */}
                {notif.unread && (
                  <span className="unread-purple-pulse-dot"></span>
                )}
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};

export default NotificationsPage;
